const Bus = [
  {
    id: "A001",
    column: 4,
    row: 6,
    seat: [
      { id: 0, seatId: "A1" },
      { id: 1, seatId: "A1" },
      { id: 2, seatId: "B1" },
      { id: 3, seatId: "C1" },
      { id: 4, seatId: "C1" },
      { id: 5, seatId: "z4" },
      { id: 6, seatId: "B2" },
      { id: 7, seatId: "C2" },
      { id: 8, seatId: "A3" },
      { id: 9, seatId: "C8" },
      { id: 10, seatId: "B3" },
      { id: 11, seatId: "C3" },
      { id: 12, seatId: "A4" },
      { id: 13, seatId: "" },
      { id: 14, seatId: "B4" },
      { id: 15, seatId: "C4" },
      { id: 16, seatId: "A5" },
      { id: 17, seatId: "F5" },
      { id: 18, seatId: "B5" },
      { id: 19, seatId: "C5" },
      { id: 20, seatId: "A6" },
      { id: 21, seatId: "G1" },
      { id: 22, seatId: "B6" },
      { id: 23, seatId: "C5" },
      //   { seatNo: A01, seatType: "seater", available: true, column: "r1" },
      //   { seatNo: A02, seatType: "seater", available: true, column: "r1" },
      //   { seatNo: A03, seatType: "seater", available: true, column: "r1" },
      //   { seatNo: A04, seatType: "seater", available: true, column: "r1" },
      //   { seatNo: A05, seatType: "seater", available: true, column: "r1" },
      //   { seatNo: B01, seatType: "seater", available: true, column: "r2" },
      //   { seatNo: B02, seatType: "seater", available: true, column: "r2" },
      //   { seatNo: B03, seatType: "seater", available: true, column: "r2" },
      //   { seatNo: B04, seatType: "seater", available: true, column: "r2" },
      //   { seatNo: B05, seatType: "seater", available: true, column: "r2" },
      //   { seatNo: C01, seatType: "seater", available: true, column: "r3" },
      //   { seatNo: C02, seatType: "seater", available: true, column: "r3" },
      //   { seatNo: C03, seatType: "seater", available: true, column: "r3" },
      //   { seatNo: C04, seatType: "seater", available: true, column: "r3" },
      //   { seatNo: C05, seatType: "seater", available: true, column: "r3" },
    ],
  },
];

export default Bus;
